-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.6.21-log - MySQL Community Server (GPL)
-- Server OS:                    Win32
-- HeidiSQL Version:             9.1.0.4867
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping database structure for dev_featextr
CREATE DATABASE IF NOT EXISTS `dev_featextr` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `dev_featextr`;


-- Dumping structure for table dev_featextr.analysis_all
CREATE TABLE IF NOT EXISTS `analysis_all` (
  `Analysis_Key` int(11) NOT NULL AUTO_INCREMENT,
  `Array_ID` int(11) NOT NULL,
  `ROI_ID` int(11) NOT NULL,
  `Num_of_probes` int(11) DEFAULT NULL,
  `Green_del_probes_90` int(11) DEFAULT NULL,
  `Green_del_probes_95` int(11) DEFAULT NULL,
  `Red_del_probes_90` int(11) DEFAULT NULL,
  `Red_del_probes_95` int(11) DEFAULT NULL,
  `Green_dup_probes_90` int(11) DEFAULT NULL,
  `Green_dup_probes_95` int(11) DEFAULT NULL,
  `Red_dup_probes_90` int(11) DEFAULT NULL,
  `Red_dup_probes_95` int(11) DEFAULT NULL,
  `GreenDelRegionScore90` int(11) DEFAULT NULL,
  `GreenDelRegionScore95` int(11) DEFAULT NULL,
  `GreenDupRegionScore90` int(11) DEFAULT NULL,
  `GreenDupRegionScore95` int(11) DEFAULT NULL,
  `RedDelRegionScore90` int(11) DEFAULT NULL,
  `RedDelRegionScore95` int(11) DEFAULT NULL,
  `RedDupRegionScore90` int(11) DEFAULT NULL,
  `RedDupRegionScore95` int(11) DEFAULT NULL,
  PRIMARY KEY (`Analysis_Key`),
  KEY `Array_ID` (`Array_ID`),
  KEY `ROI_ID` (`ROI_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

-- Data exporting was unselected.


-- Dumping structure for table dev_featextr.analysis_wbs_copy
CREATE TABLE IF NOT EXISTS `analysis_wbs_copy` (
  `ArrayID` int(11) NOT NULL,
  `GREEN_probes_outside_90` int(11) DEFAULT NULL,
  `GREEN_probes_outside_95` int(11) DEFAULT NULL,
  `RED_probes_outside_90` int(11) DEFAULT NULL,
  `RED_probes_outside_95` int(11) DEFAULT NULL,
  `Num_of_probes` int(11) DEFAULT NULL,
  `GreenRegionScore90` int(11) DEFAULT NULL,
  `GreenRegionScore95` int(11) DEFAULT NULL,
  `RedRegionScore90` int(11) DEFAULT NULL,
  `RedRegionscore95` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

-- Data exporting was unselected.


-- Dumping structure for table dev_featextr.features
CREATE TABLE IF NOT EXISTS `features` (
  `Feature_ID` int(11) NOT NULL AUTO_INCREMENT,
  `Array_ID` int(11) DEFAULT NULL,
  `FeatureNum` int(11) DEFAULT NULL,
  `Row` int(11) DEFAULT NULL,
  `Col` int(11) DEFAULT NULL,
  `SubTypeMask` int(11) DEFAULT NULL,
  `ControlType` int(11) DEFAULT NULL,
  `ProbeName` varchar(50) DEFAULT NULL,
  `ProbeKey` varchar(50) DEFAULT NULL,
  `SystematicName` varchar(50) DEFAULT NULL,
  `Chromosome` varchar(50) DEFAULT NULL,
  `Start` int(11) DEFAULT NULL,
  `Stop` int(11) DEFAULT NULL,
  `PositionX` float DEFAULT NULL,
  `PositionY` float DEFAULT NULL,
  `LogRatio` float DEFAULT NULL,
  `LogRatioError` float DEFAULT NULL,
  `PValueLogRatio` float DEFAULT NULL,
  `gProcessedSignal` float DEFAULT NULL,
  `rProcessedSignal` float DEFAULT NULL,
  `gProcessedSigError` float DEFAULT NULL,
  `rProcessedSigError` float DEFAULT NULL,
  `gMedianSignal` float DEFAULT NULL,
  `rMedianSignal` float DEFAULT NULL,
  `gBGMedianSignal` float DEFAULT NULL,
  `rBGMedianSignal` float DEFAULT NULL,
  `gBGPixSDev` float DEFAULT NULL,
  `rBGPixSDev` float DEFAULT NULL,
  `gIsSaturated` int(11) DEFAULT NULL,
  `rIsSaturated` int(11) DEFAULT NULL,
  `gIsFeatNonUnifOL` int(11) DEFAULT NULL,
  `rIsFeatNonUnifOL` int(11) DEFAULT NULL,
  `gIsBGNonUnifOL` int(11) DEFAULT NULL,
  `rIsBGNonUnifOL` int(11) DEFAULT NULL,
  `gIsFeatPopnOL` int(11) DEFAULT NULL,
  `rIsFeatPopnOL` int(11) DEFAULT NULL,
  `gIsBGPopnOL` int(11) DEFAULT NULL,
  `rIsBGPopnOL` int(11) DEFAULT NULL,
  `IsManualFlag` int(11) DEFAULT NULL,
  `gBGSubSignal` float DEFAULT NULL,
  `rBGSubSignal` float DEFAULT NULL,
  `gIsPosAndSignif` int(11) DEFAULT NULL,
  `rIsPosAndSignif` int(11) DEFAULT NULL,
  `gIsWellAboveBG` int(11) DEFAULT NULL,
  `rIsWellAboveBG` int(11) DEFAULT NULL,
  `SpotExtentX` float DEFAULT NULL,
  `gBGMeanSignal` float DEFAULT NULL,
  `rBGMeanSignal` float DEFAULT NULL,
  `Date_added` datetime DEFAULT CURRENT_TIMESTAMP,
  `GreenLogRatio` float DEFAULT NULL,
  `RedLogRatio` float DEFAULT NULL,
  `gReferenceAverageUsed` float DEFAULT NULL,
  `rReferenceAverageUsed` float DEFAULT NULL,
  `gReferenceSD` float DEFAULT NULL,
  `rReferenceSD` float DEFAULT NULL,
  `greensigintzscore` float DEFAULT NULL,
  `redsigintzscore` float DEFAULT NULL,
  `consecutive_probes_G` float DEFAULT NULL,
  `consecutive_probes_R` float DEFAULT NULL,
  PRIMARY KEY (`Feature_ID`),
  KEY `Array_ID` (`Array_ID`),
  KEY `ProbeName` (`ProbeName`),
  KEY `SystematicName` (`SystematicName`),
  KEY `ControlType` (`ControlType`),
  KEY `ProbeKey` (`ProbeKey`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

-- Data exporting was unselected.


-- Dumping structure for table dev_featextr.feparam
CREATE TABLE IF NOT EXISTS `feparam` (
  `Array_ID` int(11) NOT NULL AUTO_INCREMENT,
  `FileName` varchar(100) DEFAULT NULL,
  `ProtocolName` varchar(50) DEFAULT NULL,
  `ProtocolDate` varchar(50) DEFAULT NULL,
  `Scan_ScannerName` varchar(50) DEFAULT NULL,
  `Scan_NumChannels` int(11) DEFAULT NULL,
  `Scan_Date` varchar(50) DEFAULT NULL,
  `Scan_MicronsPerPixelX` int(11) DEFAULT NULL,
  `Scan_MicronsPerPixelY` int(11) DEFAULT NULL,
  `Scan_OriginalGUID` varchar(50) DEFAULT NULL,
  `Scan_NumScanPass` int(11) DEFAULT NULL,
  `Grid_Name` varchar(50) DEFAULT NULL,
  `Grid_Date` varchar(50) DEFAULT NULL,
  `Grid_NumSubGridRows` int(11) DEFAULT NULL,
  `Grid_NumSubGridCols` int(11) DEFAULT NULL,
  `Grid_NumRows` int(11) DEFAULT NULL,
  `Grid_NumCols` int(11) DEFAULT NULL,
  `Grid_RowSpacing` float DEFAULT NULL,
  `Grid_ColSpacing` float DEFAULT NULL,
  `Grid_OffsetX` float DEFAULT NULL,
  `Grid_OffsetY` float DEFAULT NULL,
  `Grid_NomSpotWidth` float DEFAULT NULL,
  `Grid_NomSpotHeight` float DEFAULT NULL,
  `Grid_GenomicBuild` varchar(50) DEFAULT NULL,
  `FeatureExtractor_Barcode` varchar(50) DEFAULT NULL,
  `FeatureExtractor_Sample` varchar(50) DEFAULT NULL,
  `FeatureExtractor_ScanFileName` varchar(50) DEFAULT NULL,
  `FeatureExtractor_ArrayName` varchar(50) DEFAULT NULL,
  `FeatureExtractor_ScanFileGUID` varchar(50) DEFAULT NULL,
  `FeatureExtractor_DesignFileName` varchar(50) DEFAULT NULL,
  `FeatureExtractor_ExtractionTime` varchar(50) DEFAULT NULL,
  `FeatureExtractor_UserName` varchar(50) DEFAULT NULL,
  `FeatureExtractor_ComputerName` varchar(50) DEFAULT NULL,
  `FeatureExtractor_Version` varchar(50) DEFAULT NULL,
  `FeatureExtractor_IsXDRExtraction` int(11) DEFAULT NULL,
  `FeatureExtractor_ColorMode` int(11) DEFAULT NULL,
  `FeatureExtractor_QCReportType` int(11) DEFAULT NULL,
  `DyeNorm_NormFilename` varchar(50) DEFAULT NULL,
  `DyeNorm_NormNumProbes` int(11) DEFAULT NULL,
  `Grid_IsGridFile` int(11) DEFAULT NULL,
  `Date_added` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Array_ID`),
  UNIQUE KEY `FileName` (`FileName`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

-- Data exporting was unselected.


-- Dumping structure for table dev_featextr.insert_stats
CREATE TABLE IF NOT EXISTS `insert_stats` (
  `Array_ID` int(11) NOT NULL,
  `Start_time` time DEFAULT NULL,
  `Ins_time` time DEFAULT NULL,
  `Zscore_time` time DEFAULT NULL,
  `Analysis_end_time` time DEFAULT NULL,
  `TotalTime` time DEFAULT NULL,
  PRIMARY KEY (`Array_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Data exporting was unselected.


-- Dumping structure for table dev_featextr.probeorder
CREATE TABLE IF NOT EXISTS `probeorder` (
  `Probeorder_ID` int(11) NOT NULL AUTO_INCREMENT,
  `SystematicName` varchar(50) DEFAULT NULL,
  `Start` int(11) DEFAULT NULL,
  `Stop` int(11) DEFAULT NULL,
  `Chromosome` varchar(50) DEFAULT NULL,
  `ChromosomeNumber` int(11) NOT NULL DEFAULT '0',
  `ProbeName` varchar(50) NOT NULL DEFAULT '0',
  `ProbeKey` int(11) NOT NULL DEFAULT '0',
  `Target_probe` int(11) DEFAULT NULL,
  PRIMARY KEY (`Probeorder_ID`),
  KEY `ProbeName` (`ProbeName`),
  KEY `SystematicName` (`SystematicName`),
  KEY `ProbeKey` (`ProbeKey`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

-- Data exporting was unselected.


-- Dumping structure for table dev_featextr.referencevalues
CREATE TABLE IF NOT EXISTS `referencevalues` (
  `ProbeName` varchar(50) NOT NULL,
  `ProbeKey` int(11) NOT NULL AUTO_INCREMENT,
  `gSignalInt` float DEFAULT NULL,
  `rSignalInt` float DEFAULT NULL,
  `gSignalIntSD` float DEFAULT NULL,
  `rSignalIntSD` float DEFAULT NULL,
  PRIMARY KEY (`ProbeKey`),
  UNIQUE KEY `ProbeName` (`ProbeName`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Data exporting was unselected.


-- Dumping structure for table dev_featextr.roi
CREATE TABLE IF NOT EXISTS `roi` (
  `ROI_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ROI_Name` varchar(500) DEFAULT NULL,
  `Chromosome` varchar(50) DEFAULT NULL,
  `ChromosomeNumber` int(11) DEFAULT NULL,
  `Start` int(11) DEFAULT NULL,
  `Stop` int(11) DEFAULT NULL,
  `Size` int(11) DEFAULT NULL,
  `Analysis_table` varchar(50) DEFAULT NULL,
  `Analyse` int(11) DEFAULT NULL,
  PRIMARY KEY (`ROI_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Data exporting was unselected.


-- Dumping structure for table dev_featextr.shared_imbalances
CREATE TABLE IF NOT EXISTS `shared_imbalances` (
  `Imbalance_ID` int(11) NOT NULL AUTO_INCREMENT,
  `Array_ID` int(11) DEFAULT NULL,
  `ROI_ID` int(11) DEFAULT NULL,
  `Del_Dup` int(11) DEFAULT NULL,
  `No_of_Red_probes` int(11) DEFAULT NULL,
  `No_of_Green_probes` int(11) DEFAULT NULL,
  `Probes_in_ROI` int(11) DEFAULT NULL,
  PRIMARY KEY (`Imbalance_ID`),
  KEY `Array_ID` (`Array_ID`),
  KEY `ROI_ID` (`ROI_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Data exporting was unselected.


-- Dumping structure for table dev_featextr.stats
CREATE TABLE IF NOT EXISTS `stats` (
  `Array_ID` int(11) NOT NULL,
  `gDarkOffsetAverage` float DEFAULT NULL,
  `gDarkOffsetMedian` float DEFAULT NULL,
  `gDarkOffsetStdDev` float DEFAULT NULL,
  `gDarkOffsetNumPts` int(11) DEFAULT NULL,
  `gSaturationValue` int(11) DEFAULT NULL,
  `rDarkOffsetAverage` float DEFAULT NULL,
  `rDarkOffsetMedian` float DEFAULT NULL,
  `rDarkOffsetStdDev` float DEFAULT NULL,
  `rDarkOffsetNumPts` int(11) DEFAULT NULL,
  `rSaturationValue` int(11) DEFAULT NULL,
  `gAvgSig2BkgNegCtrl` float DEFAULT NULL,
  `rAvgSig2BkgNegCtrl` float DEFAULT NULL,
  `gNumSatFeat` int(11) DEFAULT NULL,
  `gLocalBGInlierNetAve` float DEFAULT NULL,
  `gLocalBGInlierAve` float DEFAULT NULL,
  `gLocalBGInlierSDev` float DEFAULT NULL,
  `gLocalBGInlierNum` int(11) DEFAULT NULL,
  `gGlobalBGInlierAve` float DEFAULT NULL,
  `gGlobalBGInlierSDev` float DEFAULT NULL,
  `gGlobalBGInlierNum` int(11) DEFAULT NULL,
  `rNumSatFeat` int(11) DEFAULT NULL,
  `rLocalBGInlierNetAve` float DEFAULT NULL,
  `rLocalBGInlierAve` float DEFAULT NULL,
  `rLocalBGInlierSDev` float DEFAULT NULL,
  `rLocalBGInlierNum` int(11) DEFAULT NULL,
  `rGlobalBGInlierAve` float DEFAULT NULL,
  `rGlobalBGInlierSDev` float DEFAULT NULL,
  `rGlobalBGInlierNum` int(11) DEFAULT NULL,
  `gNumFeatureNonUnifOL` int(11) DEFAULT NULL,
  `gNumPopnOL` int(11) DEFAULT NULL,
  `gNumNonUnifBGOL` int(11) DEFAULT NULL,
  `gNumPopnBGOL` int(11) DEFAULT NULL,
  `gOffsetUsed` float DEFAULT NULL,
  `gGlobalFeatInlierAve` float DEFAULT NULL,
  `gGlobalFeatInlierSDev` float DEFAULT NULL,
  `gGlobalFeatInlierNum` int(11) DEFAULT NULL,
  `rNumFeatureNonUnifOL` int(11) DEFAULT NULL,
  `rNumPopnOL` int(11) DEFAULT NULL,
  `rNumNonUnifBGOL` int(11) DEFAULT NULL,
  `rNumPopnBGOL` int(11) DEFAULT NULL,
  `rOffsetUsed` float DEFAULT NULL,
  `rGlobalFeatInlierAve` float DEFAULT NULL,
  `rGlobalFeatInlierSDev` float DEFAULT NULL,
  `rGlobalFeatInlierNum` int(11) DEFAULT NULL,
  `AllColorPrcntSat` float DEFAULT NULL,
  `AnyColorPrcntSat` float DEFAULT NULL,
  `AnyColorPrcntFeatNonUnifOL` float DEFAULT NULL,
  `AnyColorPrcntBGNonUnifOL` float DEFAULT NULL,
  `AnyColorPrcntFeatPopnOL` float DEFAULT NULL,
  `AnyColorPrcntBGPopnOL` float DEFAULT NULL,
  `TotalPrcntFeatOL` float DEFAULT NULL,
  `gNumNegBGSubFeat` int(11) DEFAULT NULL,
  `gNonCtrlNumNegFeatBGSubSig` int(11) DEFAULT NULL,
  `gLinearDyeNormFactor` float DEFAULT NULL,
  `gRMSLowessDNF` float DEFAULT NULL,
  `rNumNegBGSubFeat` int(11) DEFAULT NULL,
  `rNonCtrlNumNegFeatBGSubSig` int(11) DEFAULT NULL,
  `rLinearDyeNormFactor` float DEFAULT NULL,
  `rRMSLowessDNF` float DEFAULT NULL,
  `gSpatialDetrendRMSFit` float DEFAULT NULL,
  `gSpatialDetrendRMSFilteredMinusFit` float DEFAULT NULL,
  `gSpatialDetrendSurfaceArea` float DEFAULT NULL,
  `gSpatialDetrendVolume` float DEFAULT NULL,
  `gSpatialDetrendAveFit` float DEFAULT NULL,
  `rSpatialDetrendRMSFit` float DEFAULT NULL,
  `rSpatialDetrendRMSFilteredMinusFit` float DEFAULT NULL,
  `rSpatialDetrendSurfaceArea` float DEFAULT NULL,
  `rSpatialDetrendVolume` float DEFAULT NULL,
  `rSpatialDetrendAveFit` float DEFAULT NULL,
  `gNonCtrlNumSatFeat` int(11) DEFAULT NULL,
  `gNonCtrl99PrcntNetSig` float DEFAULT NULL,
  `gNonCtrl50PrcntNetSig` float DEFAULT NULL,
  `gNonCtrl1PrcntNetSig` float DEFAULT NULL,
  `gNonCtrlMedPrcntCVBGSubSig` float DEFAULT NULL,
  `rNonCtrlNumSatFeat` int(11) DEFAULT NULL,
  `rNonCtrl99PrcntNetSig` float DEFAULT NULL,
  `rNonCtrl50PrcntNetSig` float DEFAULT NULL,
  `rNonCtrl1PrcntNetSig` float DEFAULT NULL,
  `rNonCtrlMedPrcntCVBGSubSig` float DEFAULT NULL,
  `gNegCtrlNumInliers` int(11) DEFAULT NULL,
  `gNegCtrlAveNetSig` float DEFAULT NULL,
  `gNegCtrlSDevNetSig` float DEFAULT NULL,
  `gNegCtrlAveBGSubSig` float DEFAULT NULL,
  `gNegCtrlSDevBGSubSig` float DEFAULT NULL,
  `rNegCtrlNumInliers` int(11) DEFAULT NULL,
  `rNegCtrlAveNetSig` float DEFAULT NULL,
  `rNegCtrlSDevNetSig` float DEFAULT NULL,
  `rNegCtrlAveBGSubSig` float DEFAULT NULL,
  `rNegCtrlSDevBGSubSig` float DEFAULT NULL,
  `gAveNumPixOLLo` float DEFAULT NULL,
  `gAveNumPixOLHi` float DEFAULT NULL,
  `gPixCVofHighSignalFeat` float DEFAULT NULL,
  `gNumHighSignalFeat` int(11) DEFAULT NULL,
  `rAveNumPixOLLo` float DEFAULT NULL,
  `rAveNumPixOLHi` float DEFAULT NULL,
  `rPixCVofHighSignalFeat` float DEFAULT NULL,
  `rNumHighSignalFeat` int(11) DEFAULT NULL,
  `NonCtrlAbsAveLogRatio` float DEFAULT NULL,
  `NonCtrlSDevLogRatio` float DEFAULT NULL,
  `NonCtrlSNRLogRatio` float DEFAULT NULL,
  `AddErrorEstimateGreen` float DEFAULT NULL,
  `AddErrorEstimateRed` float DEFAULT NULL,
  `TotalNumFeatures` int(11) DEFAULT NULL,
  `NonCtrlNumUpReg` int(11) DEFAULT NULL,
  `NonCtrlNumDownReg` int(11) DEFAULT NULL,
  `NumIsNorm` int(11) DEFAULT NULL,
  `ROIHeight` float DEFAULT NULL,
  `ROIWidth` float DEFAULT NULL,
  `CentroidDiffX` float DEFAULT NULL,
  `CentroidDiffY` float DEFAULT NULL,
  `NumFoundFeat` int(11) DEFAULT NULL,
  `MaxNonUnifEdges` float DEFAULT NULL,
  `MaxSpotNotFoundEdges` float DEFAULT NULL,
  `gMultDetrendRMSFit` float DEFAULT NULL,
  `rMultDetrendRMSFit` float DEFAULT NULL,
  `gMultDetrendSurfaceAverage` float DEFAULT NULL,
  `rMultDetrendSurfaceAverage` float DEFAULT NULL,
  `DerivativeOfLogRatioSD` float DEFAULT NULL,
  `gNonCtrl50PrcntBGSubSig` float DEFAULT NULL,
  `rNonCtrl50PrcntBGSubSig` float DEFAULT NULL,
  `gMedPrcntCVProcSignal` float DEFAULT NULL,
  `rMedPrcntCVProcSignal` float DEFAULT NULL,
  `geQCMedPrcntCVProcSignal` float DEFAULT NULL,
  `reQCMedPrcntCVProcSignal` float DEFAULT NULL,
  `gOutlierFlagger_Auto_FeatB_Term` float DEFAULT NULL,
  `rOutlierFlagger_Auto_FeatB_Term` float DEFAULT NULL,
  `gOutlierFlagger_Auto_FeatC_Term` float DEFAULT NULL,
  `rOutlierFlagger_Auto_FeatC_Term` float DEFAULT NULL,
  `gOutlierFlagger_Auto_BgndB_Term` float DEFAULT NULL,
  `rOutlierFlagger_Auto_BgndB_Term` float DEFAULT NULL,
  `gOutlierFlagger_Auto_BgndC_Term` float DEFAULT NULL,
  `rOutlierFlagger_Auto_BgndC_Term` float DEFAULT NULL,
  `OutlierFlagger_FeatChiSq` float DEFAULT NULL,
  `OutlierFlagger_BgndChiSq` float DEFAULT NULL,
  `GriddingStatus` int(11) DEFAULT NULL,
  `IsGoodGrid` int(11) DEFAULT NULL,
  `NumGeneNonUnifOL` int(11) DEFAULT NULL,
  `TotalNumberOfReplicatedGenes` int(11) DEFAULT NULL,
  `gPercentileIntensityProcessedSignal` float DEFAULT NULL,
  `rPercentileIntensityProcessedSignal` float DEFAULT NULL,
  `ExtractionStatus` int(11) DEFAULT NULL,
  `QCMetricResults` varchar(50) DEFAULT NULL,
  `gNonCtrlNumWellAboveBG` int(11) DEFAULT NULL,
  `rNonCtrlNumWellAboveBG` int(11) DEFAULT NULL,
  `UpRandomnessRatio` float DEFAULT NULL,
  `DownRandomnessRatio` float DEFAULT NULL,
  `UpRandomnessSDRatio` float DEFAULT NULL,
  `DownRandomnessSDRatio` float DEFAULT NULL,
  `UpRegQualityRatioResult` varchar(50) DEFAULT NULL,
  `DownRegQualityRatioResult` varchar(50) DEFAULT NULL,
  `ImageDepth` varchar(50) DEFAULT NULL,
  `AFHold` float DEFAULT NULL,
  `gPMTVolts` float DEFAULT NULL,
  `rPMTVolts` float DEFAULT NULL,
  `GlassThickness` float DEFAULT NULL,
  `RestrictionControl` float DEFAULT NULL,
  `gDDN` int(11) DEFAULT NULL,
  `rDDN` int(11) DEFAULT NULL,
  `GridHasBeenOptimized` int(11) DEFAULT NULL,
  `gNegCtrlSpread` float DEFAULT NULL,
  `rNegCtrlSpread` float DEFAULT NULL,
  `Metric_IsGoodGrid` float DEFAULT NULL,
  `Metric_IsGoodGrid_IsInRange` int(11) DEFAULT NULL,
  `Metric_AnyColorPrcntFeatNonUnifOL` float DEFAULT NULL,
  `Metric_AnyColorPrcntFeatNonUnifOL_IsInRange` int(11) DEFAULT NULL,
  `Metric_DerivativeLR_Spread` float DEFAULT NULL,
  `Metric_DerivativeLR_Spread_IsInRange` int(11) DEFAULT NULL,
  `Metric_g_Signal2Noise` float DEFAULT NULL,
  `Metric_g_Signal2Noise_IsInRange` int(11) DEFAULT NULL,
  `Metric_g_SignalIntensity` float DEFAULT NULL,
  `Metric_g_SignalIntensity_IsInRange` int(11) DEFAULT NULL,
  `Metric_r_Signal2Noise` float DEFAULT NULL,
  `Metric_r_Signal2Noise_IsInRange` int(11) DEFAULT NULL,
  `Metric_r_SignalIntensity` float DEFAULT NULL,
  `Metric_r_SignalIntensity_IsInRange` int(11) DEFAULT NULL,
  `Metric_gRepro` float DEFAULT NULL,
  `Metric_gRepro_IsInRange` int(11) DEFAULT NULL,
  `Metric_g_BGNoise` float DEFAULT NULL,
  `Metric_g_BGNoise_IsInRange` int(11) DEFAULT NULL,
  `Metric_rRepro` float DEFAULT NULL,
  `Metric_rRepro_IsInRange` int(11) DEFAULT NULL,
  `Metric_r_BGNoise` float DEFAULT NULL,
  `Metric_r_BGNoise_IsInRange` int(11) DEFAULT NULL,
  `Metric_RestrictionControl` float DEFAULT NULL,
  `Metric_RestrictionControl_IsInRange` int(11) DEFAULT NULL,
  `Metric_gDDN` float DEFAULT NULL,
  `Metric_gDDN_IsInRange` int(11) DEFAULT NULL,
  `Metric_rDDN` float DEFAULT NULL,
  `Metric_rDDN_IsInRange` int(11) DEFAULT NULL,
  `Date_added` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Array_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Data exporting was unselected.


-- Dumping structure for table dev_featextr.target_features
CREATE TABLE IF NOT EXISTS `target_features` (
  `Feature_ID` int(11) NOT NULL AUTO_INCREMENT,
  `Array_ID` int(11) DEFAULT NULL,
  `FeatureNum` int(11) DEFAULT NULL,
  `Row` int(11) DEFAULT NULL,
  `Col` int(11) DEFAULT NULL,
  `SubTypeMask` int(11) DEFAULT NULL,
  `ControlType` int(11) DEFAULT NULL,
  `ProbeName` varchar(50) DEFAULT NULL,
  `ProbeKey` varchar(50) DEFAULT NULL,
  `SystematicName` varchar(50) DEFAULT NULL,
  `Chromosome` varchar(50) DEFAULT NULL,
  `Start` int(11) DEFAULT NULL,
  `Stop` int(11) DEFAULT NULL,
  `PositionX` float DEFAULT NULL,
  `PositionY` float DEFAULT NULL,
  `LogRatio` float DEFAULT NULL,
  `LogRatioError` float DEFAULT NULL,
  `PValueLogRatio` float DEFAULT NULL,
  `gProcessedSignal` float DEFAULT NULL,
  `rProcessedSignal` float DEFAULT NULL,
  `gProcessedSigError` float DEFAULT NULL,
  `rProcessedSigError` float DEFAULT NULL,
  `gMedianSignal` float DEFAULT NULL,
  `rMedianSignal` float DEFAULT NULL,
  `gBGMedianSignal` float DEFAULT NULL,
  `rBGMedianSignal` float DEFAULT NULL,
  `gBGPixSDev` float DEFAULT NULL,
  `rBGPixSDev` float DEFAULT NULL,
  `gIsSaturated` int(11) DEFAULT NULL,
  `rIsSaturated` int(11) DEFAULT NULL,
  `gIsFeatNonUnifOL` int(11) DEFAULT NULL,
  `rIsFeatNonUnifOL` int(11) DEFAULT NULL,
  `gIsBGNonUnifOL` int(11) DEFAULT NULL,
  `rIsBGNonUnifOL` int(11) DEFAULT NULL,
  `gIsFeatPopnOL` int(11) DEFAULT NULL,
  `rIsFeatPopnOL` int(11) DEFAULT NULL,
  `gIsBGPopnOL` int(11) DEFAULT NULL,
  `rIsBGPopnOL` int(11) DEFAULT NULL,
  `IsManualFlag` int(11) DEFAULT NULL,
  `gBGSubSignal` float DEFAULT NULL,
  `rBGSubSignal` float DEFAULT NULL,
  `gIsPosAndSignif` int(11) DEFAULT NULL,
  `rIsPosAndSignif` int(11) DEFAULT NULL,
  `gIsWellAboveBG` int(11) DEFAULT NULL,
  `rIsWellAboveBG` int(11) DEFAULT NULL,
  `SpotExtentX` float DEFAULT NULL,
  `gBGMeanSignal` float DEFAULT NULL,
  `rBGMeanSignal` float DEFAULT NULL,
  `Date_added` datetime DEFAULT CURRENT_TIMESTAMP,
  `GreenLogRatio` float DEFAULT NULL,
  `RedLogRatio` float DEFAULT NULL,
  `gReferenceAverageUsed` float DEFAULT NULL,
  `rReferenceAverageUsed` float DEFAULT NULL,
  `gReferenceSD` float DEFAULT NULL,
  `rReferenceSD` float DEFAULT NULL,
  `greensigintzscore` float DEFAULT NULL,
  `redsigintzscore` float DEFAULT NULL,
  `consecutive_probes_G` float DEFAULT NULL,
  `consecutive_probes_R` float DEFAULT NULL,
  PRIMARY KEY (`Feature_ID`),
  KEY `Array_ID` (`Array_ID`),
  KEY `ProbeName` (`ProbeName`),
  KEY `SystematicName` (`SystematicName`),
  KEY `ControlType` (`ControlType`),
  KEY `ProbeKey` (`ProbeKey`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

-- Data exporting was unselected.


-- Dumping structure for table dev_featextr.target_features2
CREATE TABLE IF NOT EXISTS `target_features2` (
  `Feature_ID` int(11) NOT NULL AUTO_INCREMENT,
  `Array_ID` int(11) DEFAULT NULL,
  `FeatureNum` int(11) DEFAULT NULL,
  `Row` int(11) DEFAULT NULL,
  `Col` int(11) DEFAULT NULL,
  `SubTypeMask` int(11) DEFAULT NULL,
  `ControlType` int(11) DEFAULT NULL,
  `ProbeName` varchar(50) DEFAULT NULL,
  `ProbeKey` int(11) DEFAULT NULL,
  `SystematicName` varchar(50) DEFAULT NULL,
  `Chromosome` varchar(50) DEFAULT NULL,
  `Start` int(11) DEFAULT NULL,
  `Stop` int(11) DEFAULT NULL,
  `PositionX` float DEFAULT NULL,
  `PositionY` float DEFAULT NULL,
  `LogRatio` float DEFAULT NULL,
  `LogRatioError` float DEFAULT NULL,
  `PValueLogRatio` float DEFAULT NULL,
  `gProcessedSignal` float DEFAULT NULL,
  `rProcessedSignal` float DEFAULT NULL,
  `gProcessedSigError` float DEFAULT NULL,
  `rProcessedSigError` float DEFAULT NULL,
  `gMedianSignal` float DEFAULT NULL,
  `rMedianSignal` float DEFAULT NULL,
  `gBGMedianSignal` float DEFAULT NULL,
  `rBGMedianSignal` float DEFAULT NULL,
  `gBGPixSDev` float DEFAULT NULL,
  `rBGPixSDev` float DEFAULT NULL,
  `gIsSaturated` int(11) DEFAULT NULL,
  `rIsSaturated` int(11) DEFAULT NULL,
  `gIsFeatNonUnifOL` int(11) DEFAULT NULL,
  `rIsFeatNonUnifOL` int(11) DEFAULT NULL,
  `gIsBGNonUnifOL` int(11) DEFAULT NULL,
  `rIsBGNonUnifOL` int(11) DEFAULT NULL,
  `gIsFeatPopnOL` int(11) DEFAULT NULL,
  `rIsFeatPopnOL` int(11) DEFAULT NULL,
  `gIsBGPopnOL` int(11) DEFAULT NULL,
  `rIsBGPopnOL` int(11) DEFAULT NULL,
  `IsManualFlag` int(11) DEFAULT NULL,
  `gBGSubSignal` float DEFAULT NULL,
  `rBGSubSignal` float DEFAULT NULL,
  `gIsPosAndSignif` int(11) DEFAULT NULL,
  `rIsPosAndSignif` int(11) DEFAULT NULL,
  `gIsWellAboveBG` int(11) DEFAULT NULL,
  `rIsWellAboveBG` int(11) DEFAULT NULL,
  `SpotExtentX` float DEFAULT NULL,
  `gBGMeanSignal` float DEFAULT NULL,
  `rBGMeanSignal` float DEFAULT NULL,
  `Date_added` datetime DEFAULT CURRENT_TIMESTAMP,
  `GreenLogRatio` float DEFAULT NULL,
  `RedLogRatio` float DEFAULT NULL,
  `gReferenceAverageUsed` float DEFAULT NULL,
  `rReferenceAverageUsed` float DEFAULT NULL,
  `gReferenceSD` float DEFAULT NULL,
  `rReferenceSD` float DEFAULT NULL,
  `greensigintzscore` float DEFAULT NULL,
  `redsigintzscore` float DEFAULT NULL,
  `consecutive_probes_G` float DEFAULT NULL,
  `consecutive_probes_R` float DEFAULT NULL,
  PRIMARY KEY (`Feature_ID`),
  KEY `Array_ID` (`Array_ID`),
  KEY `ProbeName` (`ProbeName`),
  KEY `ProbeKey` (`ProbeKey`),
  CONSTRAINT `FK_target_features2_referencevalues` FOREIGN KEY (`ProbeKey`) REFERENCES `referencevalues` (`ProbeKey`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

-- Data exporting was unselected.


-- Dumping structure for table dev_featextr.test_features
CREATE TABLE IF NOT EXISTS `test_features` (
  `Feature_ID` int(11) NOT NULL AUTO_INCREMENT,
  `Array_ID` int(11) DEFAULT NULL,
  `FeatureNum` int(11) DEFAULT NULL,
  `Row` int(11) DEFAULT NULL,
  `Col` int(11) DEFAULT NULL,
  `SubTypeMask` int(11) DEFAULT NULL,
  `ControlType` int(11) DEFAULT NULL,
  `ProbeName` varchar(50) DEFAULT NULL,
  `SystematicName` varchar(50) DEFAULT NULL,
  `Chromosome` varchar(50) DEFAULT NULL,
  `Chr` varchar(50) DEFAULT NULL,
  `Start` int(11) DEFAULT NULL,
  `Stop` int(11) DEFAULT NULL,
  `PositionX` float DEFAULT NULL,
  `PositionY` float DEFAULT NULL,
  `LogRatio` float DEFAULT NULL,
  `LogRatioError` float DEFAULT NULL,
  `PValueLogRatio` float DEFAULT NULL,
  `gProcessedSignal` float DEFAULT NULL,
  `rProcessedSignal` float DEFAULT NULL,
  `gProcessedSigError` float DEFAULT NULL,
  `rProcessedSigError` float DEFAULT NULL,
  `gMedianSignal` float DEFAULT NULL,
  `rMedianSignal` float DEFAULT NULL,
  `gBGMedianSignal` float DEFAULT NULL,
  `rBGMedianSignal` float DEFAULT NULL,
  `gBGPixSDev` float DEFAULT NULL,
  `rBGPixSDev` float DEFAULT NULL,
  `gIsSaturated` int(11) DEFAULT NULL,
  `rIsSaturated` int(11) DEFAULT NULL,
  `gIsFeatNonUnifOL` int(11) DEFAULT NULL,
  `rIsFeatNonUnifOL` int(11) DEFAULT NULL,
  `gIsBGNonUnifOL` int(11) DEFAULT NULL,
  `rIsBGNonUnifOL` int(11) DEFAULT NULL,
  `gIsFeatPopnOL` int(11) DEFAULT NULL,
  `rIsFeatPopnOL` int(11) DEFAULT NULL,
  `gIsBGPopnOL` int(11) DEFAULT NULL,
  `rIsBGPopnOL` int(11) DEFAULT NULL,
  `IsManualFlag` int(11) DEFAULT NULL,
  `gBGSubSignal` float DEFAULT NULL,
  `rBGSubSignal` float DEFAULT NULL,
  `gIsPosAndSignif` int(11) DEFAULT NULL,
  `rIsPosAndSignif` int(11) DEFAULT NULL,
  `gIsWellAboveBG` int(11) DEFAULT NULL,
  `rIsWellAboveBG` int(11) DEFAULT NULL,
  `SpotExtentX` float DEFAULT NULL,
  `gBGMeanSignal` float DEFAULT NULL,
  `rBGMeanSignal` float DEFAULT NULL,
  `Date_added` datetime DEFAULT CURRENT_TIMESTAMP,
  `RedLogRatio` float DEFAULT NULL,
  `GreenLogRatio` float DEFAULT NULL,
  `rReferenceAverageUsed` float DEFAULT NULL,
  `gReferenceAverageUsed` float DEFAULT NULL,
  `rReferenceSD` float DEFAULT NULL,
  `gReferenceSD` float DEFAULT NULL,
  `RedSigIntZScore` float DEFAULT NULL,
  `GreenSigIntZScore` float DEFAULT NULL,
  PRIMARY KEY (`Feature_ID`),
  KEY `Array_ID` (`Array_ID`),
  KEY `ProbeName` (`ProbeName`),
  KEY `SystematicName` (`SystematicName`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

-- Data exporting was unselected.


-- Dumping structure for table dev_featextr.williams_analysis
CREATE TABLE IF NOT EXISTS `williams_analysis` (
  `ArrayID` int(11) NOT NULL,
  `GREEN_probes_outside_90` int(11) DEFAULT NULL,
  `GREEN_probes_outside_95` int(11) DEFAULT NULL,
  `RED_probes_outside_90` int(11) DEFAULT NULL,
  `RED_probes_outside_95` int(11) DEFAULT NULL,
  `Num_of_probes` int(11) DEFAULT NULL,
  `GreenRegionScore90` int(11) DEFAULT NULL,
  `GreenRegionScore95` int(11) DEFAULT NULL,
  `RedRegionScore90` int(11) DEFAULT NULL,
  `RedRegionscore95` int(11) DEFAULT NULL,
  PRIMARY KEY (`ArrayID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Data exporting was unselected.


-- Dumping structure for table dev_featextr.williams_features
CREATE TABLE IF NOT EXISTS `williams_features` (
  `Feature_ID` int(11) NOT NULL AUTO_INCREMENT,
  `Array_ID` int(11) DEFAULT NULL,
  `FeatureNum` int(11) DEFAULT NULL,
  `Row` int(11) DEFAULT NULL,
  `Col` int(11) DEFAULT NULL,
  `SubTypeMask` int(11) DEFAULT NULL,
  `ControlType` int(11) DEFAULT NULL,
  `ProbeName` varchar(50) DEFAULT NULL,
  `SystematicName` varchar(50) DEFAULT NULL,
  `Chromosome` varchar(50) DEFAULT NULL,
  `Start` int(11) DEFAULT NULL,
  `Stop` int(11) DEFAULT NULL,
  `PositionX` float DEFAULT NULL,
  `PositionY` float DEFAULT NULL,
  `LogRatio` float DEFAULT NULL,
  `LogRatioError` float DEFAULT NULL,
  `PValueLogRatio` float DEFAULT NULL,
  `gProcessedSignal` float DEFAULT NULL,
  `rProcessedSignal` float DEFAULT NULL,
  `gProcessedSigError` float DEFAULT NULL,
  `rProcessedSigError` float DEFAULT NULL,
  `gMedianSignal` float DEFAULT NULL,
  `rMedianSignal` float DEFAULT NULL,
  `gBGMedianSignal` float DEFAULT NULL,
  `rBGMedianSignal` float DEFAULT NULL,
  `gBGPixSDev` float DEFAULT NULL,
  `rBGPixSDev` float DEFAULT NULL,
  `gIsSaturated` int(11) DEFAULT NULL,
  `rIsSaturated` int(11) DEFAULT NULL,
  `gIsFeatNonUnifOL` int(11) DEFAULT NULL,
  `rIsFeatNonUnifOL` int(11) DEFAULT NULL,
  `gIsBGNonUnifOL` int(11) DEFAULT NULL,
  `rIsBGNonUnifOL` int(11) DEFAULT NULL,
  `gIsFeatPopnOL` int(11) DEFAULT NULL,
  `rIsFeatPopnOL` int(11) DEFAULT NULL,
  `gIsBGPopnOL` int(11) DEFAULT NULL,
  `rIsBGPopnOL` int(11) DEFAULT NULL,
  `IsManualFlag` int(11) DEFAULT NULL,
  `gBGSubSignal` float DEFAULT NULL,
  `rBGSubSignal` float DEFAULT NULL,
  `gIsPosAndSignif` int(11) DEFAULT NULL,
  `rIsPosAndSignif` int(11) DEFAULT NULL,
  `gIsWellAboveBG` int(11) DEFAULT NULL,
  `rIsWellAboveBG` int(11) DEFAULT NULL,
  `SpotExtentX` float DEFAULT NULL,
  `gBGMeanSignal` float DEFAULT NULL,
  `rBGMeanSignal` float DEFAULT NULL,
  `Date_added` datetime DEFAULT CURRENT_TIMESTAMP,
  `GreenLogRatio` float DEFAULT NULL,
  `RedLogRatio` float DEFAULT NULL,
  `gReferenceAverageUsed` float DEFAULT NULL,
  `rReferenceAverageUsed` float DEFAULT NULL,
  `gReferenceSD` float DEFAULT NULL,
  `rReferenceSD` float DEFAULT NULL,
  `greensigintzscore` float DEFAULT NULL,
  `redsigintzscore` float DEFAULT NULL,
  `consecutive_probes_G` float DEFAULT NULL,
  `consecutive_probes_R` float DEFAULT NULL,
  PRIMARY KEY (`Feature_ID`),
  KEY `Array_ID` (`Array_ID`),
  KEY `ProbeName` (`ProbeName`),
  KEY `SystematicName` (`SystematicName`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

-- Data exporting was unselected.


-- Dumping structure for table dev_featextr.williams_feparam
CREATE TABLE IF NOT EXISTS `williams_feparam` (
  `Array_ID` int(11) NOT NULL AUTO_INCREMENT,
  `FileName` varchar(100) DEFAULT NULL,
  `ProtocolName` varchar(50) DEFAULT NULL,
  `ProtocolDate` varchar(50) DEFAULT NULL,
  `Scan_ScannerName` varchar(50) DEFAULT NULL,
  `Scan_NumChannels` int(11) DEFAULT NULL,
  `Scan_Date` varchar(50) DEFAULT NULL,
  `Scan_MicronsPerPixelX` int(11) DEFAULT NULL,
  `Scan_MicronsPerPixelY` int(11) DEFAULT NULL,
  `Scan_OriginalGUID` varchar(50) DEFAULT NULL,
  `Scan_NumScanPass` int(11) DEFAULT NULL,
  `Grid_Name` varchar(50) DEFAULT NULL,
  `Grid_Date` varchar(50) DEFAULT NULL,
  `Grid_NumSubGridRows` int(11) DEFAULT NULL,
  `Grid_NumSubGridCols` int(11) DEFAULT NULL,
  `Grid_NumRows` int(11) DEFAULT NULL,
  `Grid_NumCols` int(11) DEFAULT NULL,
  `Grid_RowSpacing` float DEFAULT NULL,
  `Grid_ColSpacing` float DEFAULT NULL,
  `Grid_OffsetX` float DEFAULT NULL,
  `Grid_OffsetY` float DEFAULT NULL,
  `Grid_NomSpotWidth` float DEFAULT NULL,
  `Grid_NomSpotHeight` float DEFAULT NULL,
  `Grid_GenomicBuild` varchar(50) DEFAULT NULL,
  `FeatureExtractor_Barcode` varchar(50) DEFAULT NULL,
  `FeatureExtractor_Sample` varchar(50) DEFAULT NULL,
  `FeatureExtractor_ScanFileName` varchar(50) DEFAULT NULL,
  `FeatureExtractor_ArrayName` varchar(50) DEFAULT NULL,
  `FeatureExtractor_ScanFileGUID` varchar(50) DEFAULT NULL,
  `FeatureExtractor_DesignFileName` varchar(50) DEFAULT NULL,
  `FeatureExtractor_ExtractionTime` varchar(50) DEFAULT NULL,
  `FeatureExtractor_UserName` varchar(50) DEFAULT NULL,
  `FeatureExtractor_ComputerName` varchar(50) DEFAULT NULL,
  `FeatureExtractor_Version` varchar(50) DEFAULT NULL,
  `FeatureExtractor_IsXDRExtraction` int(11) DEFAULT NULL,
  `FeatureExtractor_ColorMode` int(11) DEFAULT NULL,
  `FeatureExtractor_QCReportType` int(11) DEFAULT NULL,
  `DyeNorm_NormFilename` varchar(50) DEFAULT NULL,
  `DyeNorm_NormNumProbes` int(11) DEFAULT NULL,
  `Grid_IsGridFile` int(11) DEFAULT NULL,
  `Date_added` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Array_ID`),
  UNIQUE KEY `FileName` (`FileName`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

-- Data exporting was unselected.


-- Dumping structure for table dev_featextr.williams_referencevalues
CREATE TABLE IF NOT EXISTS `williams_referencevalues` (
  `ProbeName` varchar(50) NOT NULL,
  `rSignalInt` float DEFAULT NULL,
  `gSignalInt` float DEFAULT NULL,
  `rSignalIntSD` float DEFAULT NULL,
  `gSignalIntSD` float DEFAULT NULL,
  PRIMARY KEY (`ProbeName`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

-- Data exporting was unselected.


-- Dumping structure for table dev_featextr.williams_stats
CREATE TABLE IF NOT EXISTS `williams_stats` (
  `Array_ID` int(11) NOT NULL,
  `gDarkOffsetAverage` float DEFAULT NULL,
  `gDarkOffsetMedian` float DEFAULT NULL,
  `gDarkOffsetStdDev` float DEFAULT NULL,
  `gDarkOffsetNumPts` int(11) DEFAULT NULL,
  `gSaturationValue` int(11) DEFAULT NULL,
  `rDarkOffsetAverage` float DEFAULT NULL,
  `rDarkOffsetMedian` float DEFAULT NULL,
  `rDarkOffsetStdDev` float DEFAULT NULL,
  `rDarkOffsetNumPts` int(11) DEFAULT NULL,
  `rSaturationValue` int(11) DEFAULT NULL,
  `gAvgSig2BkgNegCtrl` float DEFAULT NULL,
  `rAvgSig2BkgNegCtrl` float DEFAULT NULL,
  `gNumSatFeat` int(11) DEFAULT NULL,
  `gLocalBGInlierNetAve` float DEFAULT NULL,
  `gLocalBGInlierAve` float DEFAULT NULL,
  `gLocalBGInlierSDev` float DEFAULT NULL,
  `gLocalBGInlierNum` int(11) DEFAULT NULL,
  `gGlobalBGInlierAve` float DEFAULT NULL,
  `gGlobalBGInlierSDev` float DEFAULT NULL,
  `gGlobalBGInlierNum` int(11) DEFAULT NULL,
  `rNumSatFeat` int(11) DEFAULT NULL,
  `rLocalBGInlierNetAve` float DEFAULT NULL,
  `rLocalBGInlierAve` float DEFAULT NULL,
  `rLocalBGInlierSDev` float DEFAULT NULL,
  `rLocalBGInlierNum` int(11) DEFAULT NULL,
  `rGlobalBGInlierAve` float DEFAULT NULL,
  `rGlobalBGInlierSDev` float DEFAULT NULL,
  `rGlobalBGInlierNum` int(11) DEFAULT NULL,
  `gNumFeatureNonUnifOL` int(11) DEFAULT NULL,
  `gNumPopnOL` int(11) DEFAULT NULL,
  `gNumNonUnifBGOL` int(11) DEFAULT NULL,
  `gNumPopnBGOL` int(11) DEFAULT NULL,
  `gOffsetUsed` float DEFAULT NULL,
  `gGlobalFeatInlierAve` float DEFAULT NULL,
  `gGlobalFeatInlierSDev` float DEFAULT NULL,
  `gGlobalFeatInlierNum` int(11) DEFAULT NULL,
  `rNumFeatureNonUnifOL` int(11) DEFAULT NULL,
  `rNumPopnOL` int(11) DEFAULT NULL,
  `rNumNonUnifBGOL` int(11) DEFAULT NULL,
  `rNumPopnBGOL` int(11) DEFAULT NULL,
  `rOffsetUsed` float DEFAULT NULL,
  `rGlobalFeatInlierAve` float DEFAULT NULL,
  `rGlobalFeatInlierSDev` float DEFAULT NULL,
  `rGlobalFeatInlierNum` int(11) DEFAULT NULL,
  `AllColorPrcntSat` float DEFAULT NULL,
  `AnyColorPrcntSat` float DEFAULT NULL,
  `AnyColorPrcntFeatNonUnifOL` float DEFAULT NULL,
  `AnyColorPrcntBGNonUnifOL` float DEFAULT NULL,
  `AnyColorPrcntFeatPopnOL` float DEFAULT NULL,
  `AnyColorPrcntBGPopnOL` float DEFAULT NULL,
  `TotalPrcntFeatOL` float DEFAULT NULL,
  `gNumNegBGSubFeat` int(11) DEFAULT NULL,
  `gNonCtrlNumNegFeatBGSubSig` int(11) DEFAULT NULL,
  `gLinearDyeNormFactor` float DEFAULT NULL,
  `gRMSLowessDNF` float DEFAULT NULL,
  `rNumNegBGSubFeat` int(11) DEFAULT NULL,
  `rNonCtrlNumNegFeatBGSubSig` int(11) DEFAULT NULL,
  `rLinearDyeNormFactor` float DEFAULT NULL,
  `rRMSLowessDNF` float DEFAULT NULL,
  `gSpatialDetrendRMSFit` float DEFAULT NULL,
  `gSpatialDetrendRMSFilteredMinusFit` float DEFAULT NULL,
  `gSpatialDetrendSurfaceArea` float DEFAULT NULL,
  `gSpatialDetrendVolume` float DEFAULT NULL,
  `gSpatialDetrendAveFit` float DEFAULT NULL,
  `rSpatialDetrendRMSFit` float DEFAULT NULL,
  `rSpatialDetrendRMSFilteredMinusFit` float DEFAULT NULL,
  `rSpatialDetrendSurfaceArea` float DEFAULT NULL,
  `rSpatialDetrendVolume` float DEFAULT NULL,
  `rSpatialDetrendAveFit` float DEFAULT NULL,
  `gNonCtrlNumSatFeat` int(11) DEFAULT NULL,
  `gNonCtrl99PrcntNetSig` float DEFAULT NULL,
  `gNonCtrl50PrcntNetSig` float DEFAULT NULL,
  `gNonCtrl1PrcntNetSig` float DEFAULT NULL,
  `gNonCtrlMedPrcntCVBGSubSig` float DEFAULT NULL,
  `rNonCtrlNumSatFeat` int(11) DEFAULT NULL,
  `rNonCtrl99PrcntNetSig` float DEFAULT NULL,
  `rNonCtrl50PrcntNetSig` float DEFAULT NULL,
  `rNonCtrl1PrcntNetSig` float DEFAULT NULL,
  `rNonCtrlMedPrcntCVBGSubSig` float DEFAULT NULL,
  `gNegCtrlNumInliers` int(11) DEFAULT NULL,
  `gNegCtrlAveNetSig` float DEFAULT NULL,
  `gNegCtrlSDevNetSig` float DEFAULT NULL,
  `gNegCtrlAveBGSubSig` float DEFAULT NULL,
  `gNegCtrlSDevBGSubSig` float DEFAULT NULL,
  `rNegCtrlNumInliers` int(11) DEFAULT NULL,
  `rNegCtrlAveNetSig` float DEFAULT NULL,
  `rNegCtrlSDevNetSig` float DEFAULT NULL,
  `rNegCtrlAveBGSubSig` float DEFAULT NULL,
  `rNegCtrlSDevBGSubSig` float DEFAULT NULL,
  `gAveNumPixOLLo` float DEFAULT NULL,
  `gAveNumPixOLHi` float DEFAULT NULL,
  `gPixCVofHighSignalFeat` float DEFAULT NULL,
  `gNumHighSignalFeat` int(11) DEFAULT NULL,
  `rAveNumPixOLLo` float DEFAULT NULL,
  `rAveNumPixOLHi` float DEFAULT NULL,
  `rPixCVofHighSignalFeat` float DEFAULT NULL,
  `rNumHighSignalFeat` int(11) DEFAULT NULL,
  `NonCtrlAbsAveLogRatio` float DEFAULT NULL,
  `NonCtrlSDevLogRatio` float DEFAULT NULL,
  `NonCtrlSNRLogRatio` float DEFAULT NULL,
  `AddErrorEstimateGreen` float DEFAULT NULL,
  `AddErrorEstimateRed` float DEFAULT NULL,
  `TotalNumFeatures` int(11) DEFAULT NULL,
  `NonCtrlNumUpReg` int(11) DEFAULT NULL,
  `NonCtrlNumDownReg` int(11) DEFAULT NULL,
  `NumIsNorm` int(11) DEFAULT NULL,
  `ROIHeight` float DEFAULT NULL,
  `ROIWidth` float DEFAULT NULL,
  `CentroidDiffX` float DEFAULT NULL,
  `CentroidDiffY` float DEFAULT NULL,
  `NumFoundFeat` int(11) DEFAULT NULL,
  `MaxNonUnifEdges` float DEFAULT NULL,
  `MaxSpotNotFoundEdges` float DEFAULT NULL,
  `gMultDetrendRMSFit` float DEFAULT NULL,
  `rMultDetrendRMSFit` float DEFAULT NULL,
  `gMultDetrendSurfaceAverage` float DEFAULT NULL,
  `rMultDetrendSurfaceAverage` float DEFAULT NULL,
  `DerivativeOfLogRatioSD` float DEFAULT NULL,
  `gNonCtrl50PrcntBGSubSig` float DEFAULT NULL,
  `rNonCtrl50PrcntBGSubSig` float DEFAULT NULL,
  `gMedPrcntCVProcSignal` float DEFAULT NULL,
  `rMedPrcntCVProcSignal` float DEFAULT NULL,
  `geQCMedPrcntCVProcSignal` float DEFAULT NULL,
  `reQCMedPrcntCVProcSignal` float DEFAULT NULL,
  `gOutlierFlagger_Auto_FeatB_Term` float DEFAULT NULL,
  `rOutlierFlagger_Auto_FeatB_Term` float DEFAULT NULL,
  `gOutlierFlagger_Auto_FeatC_Term` float DEFAULT NULL,
  `rOutlierFlagger_Auto_FeatC_Term` float DEFAULT NULL,
  `gOutlierFlagger_Auto_BgndB_Term` float DEFAULT NULL,
  `rOutlierFlagger_Auto_BgndB_Term` float DEFAULT NULL,
  `gOutlierFlagger_Auto_BgndC_Term` float DEFAULT NULL,
  `rOutlierFlagger_Auto_BgndC_Term` float DEFAULT NULL,
  `OutlierFlagger_FeatChiSq` float DEFAULT NULL,
  `OutlierFlagger_BgndChiSq` float DEFAULT NULL,
  `GriddingStatus` int(11) DEFAULT NULL,
  `IsGoodGrid` int(11) DEFAULT NULL,
  `NumGeneNonUnifOL` int(11) DEFAULT NULL,
  `TotalNumberOfReplicatedGenes` int(11) DEFAULT NULL,
  `gPercentileIntensityProcessedSignal` float DEFAULT NULL,
  `rPercentileIntensityProcessedSignal` float DEFAULT NULL,
  `ExtractionStatus` int(11) DEFAULT NULL,
  `QCMetricResults` varchar(50) DEFAULT NULL,
  `gNonCtrlNumWellAboveBG` int(11) DEFAULT NULL,
  `rNonCtrlNumWellAboveBG` int(11) DEFAULT NULL,
  `UpRandomnessRatio` float DEFAULT NULL,
  `DownRandomnessRatio` float DEFAULT NULL,
  `UpRandomnessSDRatio` float DEFAULT NULL,
  `DownRandomnessSDRatio` float DEFAULT NULL,
  `UpRegQualityRatioResult` varchar(50) DEFAULT NULL,
  `DownRegQualityRatioResult` varchar(50) DEFAULT NULL,
  `ImageDepth` varchar(50) DEFAULT NULL,
  `AFHold` float DEFAULT NULL,
  `gPMTVolts` float DEFAULT NULL,
  `rPMTVolts` float DEFAULT NULL,
  `GlassThickness` float DEFAULT NULL,
  `RestrictionControl` float DEFAULT NULL,
  `gDDN` int(11) DEFAULT NULL,
  `rDDN` int(11) DEFAULT NULL,
  `GridHasBeenOptimized` int(11) DEFAULT NULL,
  `gNegCtrlSpread` float DEFAULT NULL,
  `rNegCtrlSpread` float DEFAULT NULL,
  `Metric_IsGoodGrid` float DEFAULT NULL,
  `Metric_IsGoodGrid_IsInRange` int(11) DEFAULT NULL,
  `Metric_AnyColorPrcntFeatNonUnifOL` float DEFAULT NULL,
  `Metric_AnyColorPrcntFeatNonUnifOL_IsInRange` int(11) DEFAULT NULL,
  `Metric_DerivativeLR_Spread` float DEFAULT NULL,
  `Metric_DerivativeLR_Spread_IsInRange` int(11) DEFAULT NULL,
  `Metric_g_Signal2Noise` float DEFAULT NULL,
  `Metric_g_Signal2Noise_IsInRange` int(11) DEFAULT NULL,
  `Metric_g_SignalIntensity` float DEFAULT NULL,
  `Metric_g_SignalIntensity_IsInRange` int(11) DEFAULT NULL,
  `Metric_r_Signal2Noise` float DEFAULT NULL,
  `Metric_r_Signal2Noise_IsInRange` int(11) DEFAULT NULL,
  `Metric_r_SignalIntensity` float DEFAULT NULL,
  `Metric_r_SignalIntensity_IsInRange` int(11) DEFAULT NULL,
  `Metric_gRepro` float DEFAULT NULL,
  `Metric_gRepro_IsInRange` int(11) DEFAULT NULL,
  `Metric_g_BGNoise` float DEFAULT NULL,
  `Metric_g_BGNoise_IsInRange` int(11) DEFAULT NULL,
  `Metric_rRepro` float DEFAULT NULL,
  `Metric_rRepro_IsInRange` int(11) DEFAULT NULL,
  `Metric_r_BGNoise` float DEFAULT NULL,
  `Metric_r_BGNoise_IsInRange` int(11) DEFAULT NULL,
  `Metric_RestrictionControl` float DEFAULT NULL,
  `Metric_RestrictionControl_IsInRange` int(11) DEFAULT NULL,
  `Metric_gDDN` float DEFAULT NULL,
  `Metric_gDDN_IsInRange` int(11) DEFAULT NULL,
  `Metric_rDDN` float DEFAULT NULL,
  `Metric_rDDN_IsInRange` int(11) DEFAULT NULL,
  `Date_added` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Array_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

-- Data exporting was unselected.


-- Dumping structure for table dev_featextr.zscore_features
CREATE TABLE IF NOT EXISTS `zscore_features` (
  `Feature_ID` int(11) NOT NULL AUTO_INCREMENT,
  `Array_ID` int(11) DEFAULT NULL,
  `FeatureNum` int(11) DEFAULT NULL,
  `Row` int(11) DEFAULT NULL,
  `Col` int(11) DEFAULT NULL,
  `SubTypeMask` int(11) DEFAULT NULL,
  `ControlType` int(11) DEFAULT NULL,
  `ProbeName` varchar(50) DEFAULT NULL,
  `SystematicName` varchar(50) DEFAULT NULL,
  `Chromosome` varchar(50) DEFAULT NULL,
  `Chr` varchar(50) DEFAULT NULL,
  `Start` int(11) DEFAULT NULL,
  `Stop` int(11) DEFAULT NULL,
  `PositionX` float DEFAULT NULL,
  `PositionY` float DEFAULT NULL,
  `LogRatio` float DEFAULT NULL,
  `LogRatioError` float DEFAULT NULL,
  `PValueLogRatio` float DEFAULT NULL,
  `gProcessedSignal` float DEFAULT NULL,
  `rProcessedSignal` float DEFAULT NULL,
  `gProcessedSigError` float DEFAULT NULL,
  `rProcessedSigError` float DEFAULT NULL,
  `gMedianSignal` float DEFAULT NULL,
  `rMedianSignal` float DEFAULT NULL,
  `gBGMedianSignal` float DEFAULT NULL,
  `rBGMedianSignal` float DEFAULT NULL,
  `gBGPixSDev` float DEFAULT NULL,
  `rBGPixSDev` float DEFAULT NULL,
  `gIsSaturated` int(11) DEFAULT NULL,
  `rIsSaturated` int(11) DEFAULT NULL,
  `gIsFeatNonUnifOL` int(11) DEFAULT NULL,
  `rIsFeatNonUnifOL` int(11) DEFAULT NULL,
  `gIsBGNonUnifOL` int(11) DEFAULT NULL,
  `rIsBGNonUnifOL` int(11) DEFAULT NULL,
  `gIsFeatPopnOL` int(11) DEFAULT NULL,
  `rIsFeatPopnOL` int(11) DEFAULT NULL,
  `gIsBGPopnOL` int(11) DEFAULT NULL,
  `rIsBGPopnOL` int(11) DEFAULT NULL,
  `IsManualFlag` int(11) DEFAULT NULL,
  `gBGSubSignal` float DEFAULT NULL,
  `rBGSubSignal` float DEFAULT NULL,
  `gIsPosAndSignif` int(11) DEFAULT NULL,
  `rIsPosAndSignif` int(11) DEFAULT NULL,
  `gIsWellAboveBG` int(11) DEFAULT NULL,
  `rIsWellAboveBG` int(11) DEFAULT NULL,
  `SpotExtentX` float DEFAULT NULL,
  `gBGMeanSignal` float DEFAULT NULL,
  `rBGMeanSignal` float DEFAULT NULL,
  `Date_added` datetime DEFAULT CURRENT_TIMESTAMP,
  `RedLogRatio` float DEFAULT NULL,
  `GreenLogRatio` float DEFAULT NULL,
  `rReferenceAverageUsed` float DEFAULT NULL,
  `gReferenceAverageUsed` float DEFAULT NULL,
  `rReferenceSD` float DEFAULT NULL,
  `gReferenceSD` float DEFAULT NULL,
  `RedSigIntZScore` float DEFAULT NULL,
  `GreenSigIntZScore` float DEFAULT NULL,
  PRIMARY KEY (`Feature_ID`),
  KEY `Array_ID` (`Array_ID`),
  KEY `ProbeName` (`ProbeName`),
  KEY `SystematicName` (`SystematicName`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

-- Data exporting was unselected.


-- Dumping structure for table dev_featextr.zscore_feparam
CREATE TABLE IF NOT EXISTS `zscore_feparam` (
  `Array_ID` int(11) NOT NULL AUTO_INCREMENT,
  `FileName` varchar(100) DEFAULT NULL,
  `ProtocolName` varchar(50) DEFAULT NULL,
  `ProtocolDate` varchar(50) DEFAULT NULL,
  `Scan_ScannerName` varchar(50) DEFAULT NULL,
  `Scan_NumChannels` int(11) DEFAULT NULL,
  `Scan_Date` varchar(50) DEFAULT NULL,
  `Scan_MicronsPerPixelX` int(11) DEFAULT NULL,
  `Scan_MicronsPerPixelY` int(11) DEFAULT NULL,
  `Scan_OriginalGUID` varchar(50) DEFAULT NULL,
  `Scan_NumScanPass` int(11) DEFAULT NULL,
  `Grid_Name` varchar(50) DEFAULT NULL,
  `Grid_Date` varchar(50) DEFAULT NULL,
  `Grid_NumSubGridRows` int(11) DEFAULT NULL,
  `Grid_NumSubGridCols` int(11) DEFAULT NULL,
  `Grid_NumRows` int(11) DEFAULT NULL,
  `Grid_NumCols` int(11) DEFAULT NULL,
  `Grid_RowSpacing` float DEFAULT NULL,
  `Grid_ColSpacing` float DEFAULT NULL,
  `Grid_OffsetX` float DEFAULT NULL,
  `Grid_OffsetY` float DEFAULT NULL,
  `Grid_NomSpotWidth` float DEFAULT NULL,
  `Grid_NomSpotHeight` float DEFAULT NULL,
  `Grid_GenomicBuild` varchar(50) DEFAULT NULL,
  `FeatureExtractor_Barcode` varchar(50) DEFAULT NULL,
  `FeatureExtractor_Sample` varchar(50) DEFAULT NULL,
  `FeatureExtractor_ScanFileName` varchar(50) DEFAULT NULL,
  `FeatureExtractor_ArrayName` varchar(50) DEFAULT NULL,
  `FeatureExtractor_ScanFileGUID` varchar(50) DEFAULT NULL,
  `FeatureExtractor_DesignFileName` varchar(50) DEFAULT NULL,
  `FeatureExtractor_ExtractionTime` varchar(50) DEFAULT NULL,
  `FeatureExtractor_UserName` varchar(50) DEFAULT NULL,
  `FeatureExtractor_ComputerName` varchar(50) DEFAULT NULL,
  `FeatureExtractor_Version` varchar(50) DEFAULT NULL,
  `FeatureExtractor_IsXDRExtraction` int(11) DEFAULT NULL,
  `FeatureExtractor_ColorMode` int(11) DEFAULT NULL,
  `FeatureExtractor_QCReportType` int(11) DEFAULT NULL,
  `DyeNorm_NormFilename` varchar(50) DEFAULT NULL,
  `DyeNorm_NormNumProbes` int(11) DEFAULT NULL,
  `Grid_IsGridFile` int(11) DEFAULT NULL,
  `Date_added` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Array_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

-- Data exporting was unselected.


-- Dumping structure for table dev_featextr.zscore_reference
CREATE TABLE IF NOT EXISTS `zscore_reference` (
  `ProbeName` varchar(50) NOT NULL,
  `gSignalInt` float DEFAULT NULL,
  `rSignalInt` float DEFAULT NULL,
  `gSignalIntSD` float DEFAULT NULL,
  `rSignalIntSD` float DEFAULT NULL,
  PRIMARY KEY (`ProbeName`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

-- Data exporting was unselected.


-- Dumping structure for table dev_featextr.zscore_stats
CREATE TABLE IF NOT EXISTS `zscore_stats` (
  `Array_ID` int(11) NOT NULL,
  `gDarkOffsetAverage` float DEFAULT NULL,
  `gDarkOffsetMedian` float DEFAULT NULL,
  `gDarkOffsetStdDev` float DEFAULT NULL,
  `gDarkOffsetNumPts` int(11) DEFAULT NULL,
  `gSaturationValue` int(11) DEFAULT NULL,
  `rDarkOffsetAverage` float DEFAULT NULL,
  `rDarkOffsetMedian` float DEFAULT NULL,
  `rDarkOffsetStdDev` float DEFAULT NULL,
  `rDarkOffsetNumPts` int(11) DEFAULT NULL,
  `rSaturationValue` int(11) DEFAULT NULL,
  `gAvgSig2BkgNegCtrl` float DEFAULT NULL,
  `rAvgSig2BkgNegCtrl` float DEFAULT NULL,
  `gNumSatFeat` int(11) DEFAULT NULL,
  `gLocalBGInlierNetAve` float DEFAULT NULL,
  `gLocalBGInlierAve` float DEFAULT NULL,
  `gLocalBGInlierSDev` float DEFAULT NULL,
  `gLocalBGInlierNum` int(11) DEFAULT NULL,
  `gGlobalBGInlierAve` float DEFAULT NULL,
  `gGlobalBGInlierSDev` float DEFAULT NULL,
  `gGlobalBGInlierNum` int(11) DEFAULT NULL,
  `rNumSatFeat` int(11) DEFAULT NULL,
  `rLocalBGInlierNetAve` float DEFAULT NULL,
  `rLocalBGInlierAve` float DEFAULT NULL,
  `rLocalBGInlierSDev` float DEFAULT NULL,
  `rLocalBGInlierNum` int(11) DEFAULT NULL,
  `rGlobalBGInlierAve` float DEFAULT NULL,
  `rGlobalBGInlierSDev` float DEFAULT NULL,
  `rGlobalBGInlierNum` int(11) DEFAULT NULL,
  `gNumFeatureNonUnifOL` int(11) DEFAULT NULL,
  `gNumPopnOL` int(11) DEFAULT NULL,
  `gNumNonUnifBGOL` int(11) DEFAULT NULL,
  `gNumPopnBGOL` int(11) DEFAULT NULL,
  `gOffsetUsed` float DEFAULT NULL,
  `gGlobalFeatInlierAve` float DEFAULT NULL,
  `gGlobalFeatInlierSDev` float DEFAULT NULL,
  `gGlobalFeatInlierNum` int(11) DEFAULT NULL,
  `rNumFeatureNonUnifOL` int(11) DEFAULT NULL,
  `rNumPopnOL` int(11) DEFAULT NULL,
  `rNumNonUnifBGOL` int(11) DEFAULT NULL,
  `rNumPopnBGOL` int(11) DEFAULT NULL,
  `rOffsetUsed` float DEFAULT NULL,
  `rGlobalFeatInlierAve` float DEFAULT NULL,
  `rGlobalFeatInlierSDev` float DEFAULT NULL,
  `rGlobalFeatInlierNum` int(11) DEFAULT NULL,
  `AllColorPrcntSat` float DEFAULT NULL,
  `AnyColorPrcntSat` float DEFAULT NULL,
  `AnyColorPrcntFeatNonUnifOL` float DEFAULT NULL,
  `AnyColorPrcntBGNonUnifOL` float DEFAULT NULL,
  `AnyColorPrcntFeatPopnOL` float DEFAULT NULL,
  `AnyColorPrcntBGPopnOL` float DEFAULT NULL,
  `TotalPrcntFeatOL` float DEFAULT NULL,
  `gNumNegBGSubFeat` int(11) DEFAULT NULL,
  `gNonCtrlNumNegFeatBGSubSig` int(11) DEFAULT NULL,
  `gLinearDyeNormFactor` float DEFAULT NULL,
  `gRMSLowessDNF` float DEFAULT NULL,
  `rNumNegBGSubFeat` int(11) DEFAULT NULL,
  `rNonCtrlNumNegFeatBGSubSig` int(11) DEFAULT NULL,
  `rLinearDyeNormFactor` float DEFAULT NULL,
  `rRMSLowessDNF` float DEFAULT NULL,
  `gSpatialDetrendRMSFit` float DEFAULT NULL,
  `gSpatialDetrendRMSFilteredMinusFit` float DEFAULT NULL,
  `gSpatialDetrendSurfaceArea` float DEFAULT NULL,
  `gSpatialDetrendVolume` float DEFAULT NULL,
  `gSpatialDetrendAveFit` float DEFAULT NULL,
  `rSpatialDetrendRMSFit` float DEFAULT NULL,
  `rSpatialDetrendRMSFilteredMinusFit` float DEFAULT NULL,
  `rSpatialDetrendSurfaceArea` float DEFAULT NULL,
  `rSpatialDetrendVolume` float DEFAULT NULL,
  `rSpatialDetrendAveFit` float DEFAULT NULL,
  `gNonCtrlNumSatFeat` int(11) DEFAULT NULL,
  `gNonCtrl99PrcntNetSig` float DEFAULT NULL,
  `gNonCtrl50PrcntNetSig` float DEFAULT NULL,
  `gNonCtrl1PrcntNetSig` float DEFAULT NULL,
  `gNonCtrlMedPrcntCVBGSubSig` float DEFAULT NULL,
  `rNonCtrlNumSatFeat` int(11) DEFAULT NULL,
  `rNonCtrl99PrcntNetSig` float DEFAULT NULL,
  `rNonCtrl50PrcntNetSig` float DEFAULT NULL,
  `rNonCtrl1PrcntNetSig` float DEFAULT NULL,
  `rNonCtrlMedPrcntCVBGSubSig` float DEFAULT NULL,
  `gNegCtrlNumInliers` int(11) DEFAULT NULL,
  `gNegCtrlAveNetSig` float DEFAULT NULL,
  `gNegCtrlSDevNetSig` float DEFAULT NULL,
  `gNegCtrlAveBGSubSig` float DEFAULT NULL,
  `gNegCtrlSDevBGSubSig` float DEFAULT NULL,
  `rNegCtrlNumInliers` int(11) DEFAULT NULL,
  `rNegCtrlAveNetSig` float DEFAULT NULL,
  `rNegCtrlSDevNetSig` float DEFAULT NULL,
  `rNegCtrlAveBGSubSig` float DEFAULT NULL,
  `rNegCtrlSDevBGSubSig` float DEFAULT NULL,
  `gAveNumPixOLLo` float DEFAULT NULL,
  `gAveNumPixOLHi` float DEFAULT NULL,
  `gPixCVofHighSignalFeat` float DEFAULT NULL,
  `gNumHighSignalFeat` int(11) DEFAULT NULL,
  `rAveNumPixOLLo` float DEFAULT NULL,
  `rAveNumPixOLHi` float DEFAULT NULL,
  `rPixCVofHighSignalFeat` float DEFAULT NULL,
  `rNumHighSignalFeat` int(11) DEFAULT NULL,
  `NonCtrlAbsAveLogRatio` float DEFAULT NULL,
  `NonCtrlSDevLogRatio` float DEFAULT NULL,
  `NonCtrlSNRLogRatio` float DEFAULT NULL,
  `AddErrorEstimateGreen` float DEFAULT NULL,
  `AddErrorEstimateRed` float DEFAULT NULL,
  `TotalNumFeatures` int(11) DEFAULT NULL,
  `NonCtrlNumUpReg` int(11) DEFAULT NULL,
  `NonCtrlNumDownReg` int(11) DEFAULT NULL,
  `NumIsNorm` int(11) DEFAULT NULL,
  `ROIHeight` float DEFAULT NULL,
  `ROIWidth` float DEFAULT NULL,
  `CentroidDiffX` float DEFAULT NULL,
  `CentroidDiffY` float DEFAULT NULL,
  `NumFoundFeat` int(11) DEFAULT NULL,
  `MaxNonUnifEdges` float DEFAULT NULL,
  `MaxSpotNotFoundEdges` float DEFAULT NULL,
  `gMultDetrendRMSFit` float DEFAULT NULL,
  `rMultDetrendRMSFit` float DEFAULT NULL,
  `gMultDetrendSurfaceAverage` float DEFAULT NULL,
  `rMultDetrendSurfaceAverage` float DEFAULT NULL,
  `DerivativeOfLogRatioSD` float DEFAULT NULL,
  `gNonCtrl50PrcntBGSubSig` float DEFAULT NULL,
  `rNonCtrl50PrcntBGSubSig` float DEFAULT NULL,
  `gMedPrcntCVProcSignal` float DEFAULT NULL,
  `rMedPrcntCVProcSignal` float DEFAULT NULL,
  `geQCMedPrcntCVProcSignal` float DEFAULT NULL,
  `reQCMedPrcntCVProcSignal` float DEFAULT NULL,
  `gOutlierFlagger_Auto_FeatB_Term` float DEFAULT NULL,
  `rOutlierFlagger_Auto_FeatB_Term` float DEFAULT NULL,
  `gOutlierFlagger_Auto_FeatC_Term` float DEFAULT NULL,
  `rOutlierFlagger_Auto_FeatC_Term` float DEFAULT NULL,
  `gOutlierFlagger_Auto_BgndB_Term` float DEFAULT NULL,
  `rOutlierFlagger_Auto_BgndB_Term` float DEFAULT NULL,
  `gOutlierFlagger_Auto_BgndC_Term` float DEFAULT NULL,
  `rOutlierFlagger_Auto_BgndC_Term` float DEFAULT NULL,
  `OutlierFlagger_FeatChiSq` float DEFAULT NULL,
  `OutlierFlagger_BgndChiSq` float DEFAULT NULL,
  `GriddingStatus` int(11) DEFAULT NULL,
  `IsGoodGrid` int(11) DEFAULT NULL,
  `NumGeneNonUnifOL` int(11) DEFAULT NULL,
  `TotalNumberOfReplicatedGenes` int(11) DEFAULT NULL,
  `gPercentileIntensityProcessedSignal` float DEFAULT NULL,
  `rPercentileIntensityProcessedSignal` float DEFAULT NULL,
  `ExtractionStatus` int(11) DEFAULT NULL,
  `QCMetricResults` varchar(50) DEFAULT NULL,
  `gNonCtrlNumWellAboveBG` int(11) DEFAULT NULL,
  `rNonCtrlNumWellAboveBG` int(11) DEFAULT NULL,
  `UpRandomnessRatio` float DEFAULT NULL,
  `DownRandomnessRatio` float DEFAULT NULL,
  `UpRandomnessSDRatio` float DEFAULT NULL,
  `DownRandomnessSDRatio` float DEFAULT NULL,
  `UpRegQualityRatioResult` varchar(50) DEFAULT NULL,
  `DownRegQualityRatioResult` varchar(50) DEFAULT NULL,
  `ImageDepth` varchar(50) DEFAULT NULL,
  `AFHold` float DEFAULT NULL,
  `gPMTVolts` float DEFAULT NULL,
  `rPMTVolts` float DEFAULT NULL,
  `GlassThickness` float DEFAULT NULL,
  `RestrictionControl` float DEFAULT NULL,
  `gDDN` int(11) DEFAULT NULL,
  `rDDN` int(11) DEFAULT NULL,
  `GridHasBeenOptimized` int(11) DEFAULT NULL,
  `gNegCtrlSpread` float DEFAULT NULL,
  `rNegCtrlSpread` float DEFAULT NULL,
  `Metric_IsGoodGrid` float DEFAULT NULL,
  `Metric_IsGoodGrid_IsInRange` int(11) DEFAULT NULL,
  `Metric_AnyColorPrcntFeatNonUnifOL` float DEFAULT NULL,
  `Metric_AnyColorPrcntFeatNonUnifOL_IsInRange` int(11) DEFAULT NULL,
  `Metric_DerivativeLR_Spread` float DEFAULT NULL,
  `Metric_DerivativeLR_Spread_IsInRange` int(11) DEFAULT NULL,
  `Metric_g_Signal2Noise` float DEFAULT NULL,
  `Metric_g_Signal2Noise_IsInRange` int(11) DEFAULT NULL,
  `Metric_g_SignalIntensity` float DEFAULT NULL,
  `Metric_g_SignalIntensity_IsInRange` int(11) DEFAULT NULL,
  `Metric_r_Signal2Noise` float DEFAULT NULL,
  `Metric_r_Signal2Noise_IsInRange` int(11) DEFAULT NULL,
  `Metric_r_SignalIntensity` float DEFAULT NULL,
  `Metric_r_SignalIntensity_IsInRange` int(11) DEFAULT NULL,
  `Metric_gRepro` float DEFAULT NULL,
  `Metric_gRepro_IsInRange` int(11) DEFAULT NULL,
  `Metric_g_BGNoise` float DEFAULT NULL,
  `Metric_g_BGNoise_IsInRange` int(11) DEFAULT NULL,
  `Metric_rRepro` float DEFAULT NULL,
  `Metric_rRepro_IsInRange` int(11) DEFAULT NULL,
  `Metric_r_BGNoise` float DEFAULT NULL,
  `Metric_r_BGNoise_IsInRange` int(11) DEFAULT NULL,
  `Metric_RestrictionControl` float DEFAULT NULL,
  `Metric_RestrictionControl_IsInRange` int(11) DEFAULT NULL,
  `Metric_gDDN` float DEFAULT NULL,
  `Metric_gDDN_IsInRange` int(11) DEFAULT NULL,
  `Metric_rDDN` float DEFAULT NULL,
  `Metric_rDDN_IsInRange` int(11) DEFAULT NULL,
  `Date_added` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Array_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

-- Data exporting was unselected.
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
